"""empty message

Revision ID: 159353c00087
Revises: 
Create Date: 2025-07-02 11:09:42.423796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159353c00087'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('bid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
